In [115]:
import numpy as np

In [14]:
# 1-d array
oned = np.array([1,2,3])
oned

array([1, 2, 3])

In [6]:
# 2-d array
twod = np.array([[1,2,3],[2,3,4]])
twod

array([[1, 2, 3],
       [2, 3, 4]])

In [18]:
#3d array
threed = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
threed


array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [16]:
type(threed)

numpy.ndarray

List to numpy

In [25]:
l1 = [1,2,3,4,5]
n1 = np.array(l1)
n1

array([1, 2, 3, 4, 5])

numpy to list

In [29]:
n1 = np.array([1,2,3])
n1

array([1, 2, 3])

In [31]:
print (type(n1))

<class 'numpy.ndarray'>


In [33]:
back_to_list = n1.tolist()
back_to_list

[1, 2, 3]

# arange

In [35]:
n1 = np.arange(10)
n1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
n1 = np.arange(1,10)
n1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
n1 = np.arange(1,10,2)
n1

array([1, 3, 5, 7, 9])

# np.zeros()

In [38]:
n1 = np.zeros(5,dtype = 'int')
n1

array([0, 0, 0, 0, 0])

## np.ones()

In [40]:
n1 = np.ones(5)
n1

array([1., 1., 1., 1., 1.])

## linspace()

In [42]:
np.linspace(2.0,3.0,num=5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [43]:
#default num is 50
np.linspace(2.0,3.0)

array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
       2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
       2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
       2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
       2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
       2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
       2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
       2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
       2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
       2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ])

In [48]:
#retstep -> it will give you range between the 2 array elements
np.linspace(2.0,3.0,num = 5,retstep=True)

(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)

In [47]:
#if we mention endpoint is False then it won't consider the end value to create an array
np.linspace(2.0,3.0,num = 5,endpoint=False ,retstep=True)

(array([2. , 2.2, 2.4, 2.6, 2.8]), 0.2)

In [64]:
x1 = np.random.randint(1,5,10)
x1

array([1, 2, 2, 1, 4, 2, 2, 1, 2, 4])

# np.eye()

In [65]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [66]:
np.eye(5,3) # m=3 so 3 columns

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [73]:
# k values will move the diagnels in positive or negative direction. 
# if the value is - then it'll go to left else it go to right
np.eye(3,k=-2)

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 0., 0.]])

In [74]:
np.eye(3,k=1,dtype=int)

array([[0, 1, 0],
       [0, 0, 1],
       [0, 0, 0]])

## np.identity()

In [77]:
# This is also similar to eye function but it only have dtype argument
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [78]:
np.identity(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

ndim

In [80]:
n1 = np.array([1,2,3])
n1.ndim

1

In [83]:
n1=np.array([[1,2,3],[1,23,43]])
n1.ndim

2

shape

In [84]:
n1=np.array([[1,2,3],[1,23,43]])
n1.shape

(2, 3)

itemsize

In [86]:
n1=np.array([[1,2,3],[1,23,43]])
print("Data type of n1:", n1.dtype)
print("Item size of n1:", n1.itemsize)

Data type of n1: int32
Item size of n1: 4


size

In [90]:
n1=np.array([[1,2,3,34],[1,23,43,43]])
print("size of n1:", n1.size)

size of n1: 8


In [4]:
# Numpy is a single data type even if one element is different data type then it'll change all the element into different data type.
# Here one element is float so it chaged all the element into float.
numpy = np.array([1,3.5,2])
numpy

array([1. , 3.5, 2. ])

In [5]:
# all converted into string
numpy = np.array([1,'ragul',2])
numpy

array(['1', 'ragul', '2'], dtype='<U11')

In [6]:
#  all converted into int
numpy = np.array([1,True,False])
numpy

array([1, 1, 0])

In [7]:
# we can't do element wise operation in list but we can do in numpy

list1 = [1,2,3]
list2 = [1,2,3]
list1+list2

[1, 2, 3, 1, 2, 3]

In [8]:
arr1 = np.array([10,20,30])
arr2 = np.array([11,21,31])

In [9]:
arr1 + arr2

array([21, 41, 61])

In [10]:
# Calculate BMI using numpy
h = np.array([1.67,1.89,1.56])

In [11]:
w = np.array([66.2,45.3,67.8])

In [18]:
bmi = w/h**2

In [19]:
bmi

array([23.73695722, 12.68161586, 27.85996055])

## Reshape

In [9]:
v = np.arange(8)

In [10]:
v.ndim

1

In [14]:
# 1D to 2D
c = np.reshape(v,(4,2))

In [15]:
c

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [18]:
# 1D to 3D

v = np.arange(16)
v

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [19]:
c = np.reshape(v,(2,2,4))
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [20]:
#2D to 3D
v = np.zeros((4,4))
v


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [23]:
v.ndim

2

In [22]:
c = np.reshape(v,(2,2,4))
c

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [24]:
#2D to 1D

v = np.zeros((4,4))
v


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [25]:
c = np.reshape(v,(16))
c

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [26]:
# np.reshape(a, newshape, order='C') - here C means row wise and F means column wise

In [27]:
a = np.arange(12)

In [28]:
a.ndim

1

In [32]:
arr1 = np.reshape(a,(6,2),order = 'C')
arr1

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [33]:
arr1 = np.reshape(a,(6,2),order = 'F')
arr1

array([[ 0,  6],
       [ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11]])

In [36]:
x = np.arange(12).reshape(4,3) # we can write it in the single line as well
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [37]:
x.reshape(-1,3) # where ever we mentioned -1 numpy will calculate the apprpriate values

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [38]:
x.reshape(2,-1) 

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [39]:
x.reshape(-1,-1) #  can only specify one unknown dimension

ValueError: can only specify one unknown dimension

In [43]:
y = np.arange(12)

In [46]:
y.reshape(-1,1) # This function is very important in machine learning

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

## resize

In [56]:
v2 = np.arange(12)

In [57]:
# array resize
v = v2.resize((6,3))

In [58]:
v # it won't return anything because array resize changed the original values of V1.for extra values it'll fill the zeros

In [59]:
v2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [ 0,  0,  0],
       [ 0,  0,  0]])

In [60]:
# numpy resize
N = np.arange(12)

In [62]:
x = np.resize(N,(4,4)) # For extra values it'll take the elements again from the start
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3]])

In [64]:
x = np.resize(N,(2,4))
x

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

## Aliasing and cloning

In [65]:
x = np.array([1,2,3,4])
x

array([1, 2, 3, 4])

In [66]:
y = x
y

array([1, 2, 3, 4])

In [67]:
x[1] = 999 # I changed the value only in x but values are changing in both the variables
x

array([  1, 999,   3,   4])

In [68]:
y

array([  1, 999,   3,   4])

In [69]:
# With slicing
x = np.array([1,2,3,4])
x

array([1, 2, 3, 4])

In [70]:
y = x[:]
y

array([1, 2, 3, 4])

In [71]:
x[1] = 888
x

array([  1, 888,   3,   4])

In [72]:
y # Even if we did slicing it won't work

array([  1, 888,   3,   4])

In [ ]:
#

In [73]:
x = np.array([1,2,3,4])
x

array([1, 2, 3, 4])

In [74]:
y = np.copy(x)
y

array([1, 2, 3, 4])

In [75]:
x[1] = 777
x

array([  1, 777,   3,   4])

In [77]:
y # with copy function it's not changing the value in both the position

array([1, 2, 3, 4])

## Copy VS View

In [78]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [79]:
y = x.view()

In [80]:
y

array([0, 1, 2, 3, 4])

In [81]:
y[1] = 789
y

array([  0, 789,   2,   3,   4])

In [82]:
x

array([  0, 789,   2,   3,   4])

In [83]:
print(x.base)

None


In [84]:
print(y.base) # Y is created based X view so both are pointing the same data so, if you change anythging in any element it'll affect both


[  0 789   2   3   4]


In [86]:
#copy
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [87]:
y1 = np.copy(x)
y1

array([0, 1, 2, 3, 4])

In [88]:
y1[1]=999
y

array([  0, 789,   2,   3,   4])

In [92]:
x

array([0, 1, 2, 3, 4])

In [90]:
print(x.base)

None


In [91]:
print(y.base)

[  0 789   2   3   4]


## Ravel Vs. Flatten Vs. Reshape(-1)

In [93]:
# Ravel - > it's similar to view it's not owning the data any change in view the data will change in both position

In [97]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [98]:
b=a.ravel()
b

array([0, 1, 2, 3, 4])

In [99]:
b[1] = 999
b

array([  0, 999,   2,   3,   4])

In [100]:
a

array([  0, 999,   2,   3,   4])

In [101]:
#Flatten - it's similar to copy it's owning the data any change in copy the data will not change in both position

In [102]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [103]:
b=a.flatten()
b

array([0, 1, 2, 3, 4])

In [104]:
b[1] = 999
b

array([  0, 999,   2,   3,   4])

In [105]:
a

array([0, 1, 2, 3, 4])

In [106]:
#reshape -> similar to view

In [107]:
a = np.arange(12).reshape(4,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [108]:
b = a.reshape(-1)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [109]:
b[1]=99
b

array([ 0, 99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [110]:
a

array([[ 0, 99,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [111]:
# Axis

In [116]:
a = np.array([[1,2],
            [3,4]])
a

array([[1, 2],
       [3, 4]])

In [113]:
a.sum(axis=0)  #axis=0 means along the columns( Top to Bottom)

array([4, 6])

In [114]:
a.sum(axis=1)  #axis=1 means along the Row( left to right)

array([3, 7])

In [118]:
a.sum() # if we don't provide any axis then it'll sum the all values

10

In [121]:
# 1*3 = 3 and 2*4 = 8 --- 3*8 =24
a.prod()

24

In [122]:
a.prod(axis=0)

array([3, 8])

In [123]:
a.prod(axis=1)

array([ 2, 12])

In [124]:
# Sort
b = np.array([1,20,2,34,5,3])
b

array([ 1, 20,  2, 34,  5,  3])

In [130]:
b.sort()
print(b)

[ 1  2  3  5 20 34]


In [134]:
a1 = np.array([[20,9],
            [3,2]])
a1

array([[20,  9],
       [ 3,  2]])

In [136]:
a1.sort(axis=0)
a1

array([[ 3,  2],
       [20,  9]])

In [137]:
a1.sort(axis=1)
a1

array([[ 2,  3],
       [ 9, 20]])

In [153]:
# V stack
a = np.array([1,2,3,4])
b = np.array([2,4,6,8])

In [154]:
x = np.vstack((a,b)) # a is stacking on top of b

In [157]:
c = np.array([0, 0, 0, 0])
c = c.reshape(1, -1)  # Reshape c to 2D with 1 row

c


array([[0, 0, 0, 0]])

In [158]:
np.vstack((c,x))

array([[0, 0, 0, 0],
       [1, 2, 3, 4],
       [2, 4, 6, 8]])

In [161]:
# 2D Vstacking
a1 = np.array([[1,2],[3,4]])
b1 = np.array([[5,6],[7,8]])

In [162]:
np.vstack((a1,b1))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
# hstack
a = np.array([1,2,3,4])
b = np.array([2,4,6,8])

In [163]:
np.hstack((a,b))

array([1, 2, 3, 4, 2, 4, 6, 8])

In [ ]:
# 2D hstack
a1 = np.array([[1,2],
               [3,4]])


b1 = np.array([[5,6],
               [7,8]])

In [166]:
np.hstack((a1,b1))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [172]:
# Split
x = np.arange(1,11)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [173]:
np.split(x,2) # It'll split the array into 2 equal parts

[array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10])]

In [174]:
np.split(x,[3]) # It'll split the array from the given position

[array([1, 2, 3]), array([ 4,  5,  6,  7,  8,  9, 10])]

In [177]:
np.split(x,[3,6]) # It'll split the array from start position to end position

In [179]:
# spliting in 2D

In [181]:
x = np.arange(16).reshape(4,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [184]:
np.split(x,2,axis=0) # here axis = 0 means split by row wise axis = 1 means split by column wise

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [185]:
np.split(x,2,axis=1)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [186]:
# Arithmetic operations
a = np.array([1,2,3,4])
b = np.array([2,4,6,8])

In [187]:
a+b #we can use the keyword np.add(a+b)

array([ 3,  6,  9, 12])

In [188]:
a-b

array([-1, -2, -3, -4])

In [189]:
a*b

array([ 2,  8, 18, 32])

In [191]:
b/a

array([2., 2., 2., 2.])

In [192]:
a//b

array([0, 0, 0, 0])

In [194]:
a**b

array([    1,    16,   729, 65536])

In [195]:
np.max(a)

4

In [196]:
np.max(b)

8

In [197]:
np.std(b)

2.23606797749979

In [199]:
np.average(a)

2.5

In [210]:
# indexing and slicing
a = np.array([1,2,3,4])
a[0:4:2]

array([1, 3])

In [212]:
a[::3]

array([1, 4])

In [ ]:
# indexing and slicing in 2D

In [213]:
a=np.arange(16).reshape(4,4)

In [214]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [216]:
a[1:,1:]

array([[ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15]])

In [217]:
a[0,0]

0

In [225]:
a[1:3,1]

array([5, 9])